owner: RichieTH
repo: bangkok-bytes-status

sites:
  - name: Bangkok Bytes
    url: https://bangkokbytes.com

status-website:
  cname: status.bangkokbytes.com
  logoUrl: https://bangkokbytes.com/favicon.svg
  name: Bangkok Bytes Status
  introTitle: "**Bangkok Bytes Status**"
  introMessage: We use open-source tools to monitor our uptime — powered entirely by GitHub Actions. Stay informed about the health of our blog, APIs, and services.
  navbar:
    - title: Home
      href: https://bangkokbytes.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/RichieTH/bangkok-bytes-status
